DROP TABLE PRODUCT CASCADE CONSTRAINTS
DROP TABLE SEMI_MEMBER CASCADE CONSTRAINTS
DROP TABLE QNA CASCADE CONSTRAINTS;
DROP TABLE BUYHISTORY CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_QNA;
DROP SEQUENCE SEQ_PRODUCT;

select *from product 



CREATE TABLE PRODUCT(
	SEQ VARCHAR2 (100) PRIMARY KEY, --상품번호
	PRODUCT_NAME VARCHAR2(100) NOT NULL, --상품이름
	BN_PRICE NUMBER NOT NULL, --즉결가
	START_PRICE NUMBER NOT NULL, --시작가
	EXPLN VARCHAR2 (4000) NOT NULL, --상품설명
	PIC VARCHAR2 (4000), --상품이미지(경로)
	CATEGORY VARCHAR2 (100) NOT NULL, --카테고리
	ID VARCHAR2 (100) NOT NULL,  --작성자 ID
	WDATE DATE, --작성날짜
	EDATE DATE, --판매종료일
	SELL_STATUS NUMBER  NOT NULL, --구매진행상태
	BUYER VARCHAR2(100) NOT NULL,  --구매자 ID
	STATUS NUMBER NOT NULL --상품상태(중고/신품)
);

CREATE SEQUENCE SEQ_PRODUCT
START WITH 1
INCREMENT BY 1;

CREATE TABLE SEMI_MEMBER(
NAME VARCHAR2 (100), --이름
ID VARCHAR2(100) PRIMARY KEY, --ID
PWD VARCHAR2(50) NOT NULL,
ADDRESS VARCHAR2(200) NOT NULL, --주소
BIRTH VARCHAR2(100) NOT NULL, --생년월일
QFQUESTION NUMBER NOT NULL, --비밀번호 질문
QFANSWER VARCHAR2(50) NOT NULL,
AUTH NUMBER NOT NULL --회원등급
);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_BUYER FOREIGN KEY(ID)
REFERENCES SEMI_MEMBER(ID)




CREATE TABLE QNA_PRO(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WDATE DATE NOT NULL,
	DEL NUMBER(1) NOT NULL,
	READCOUNT NUMBER(8) NOT NULL,
	
	REF NUMBER(8) NOT NULL,
	STEP NUMBER(8) NOT NULL,
	DEPTH NUMBER(8) NOT NULL,
	
	PARENT NUMBER(8) NOT NULL
);

CREATE SEQUENCE SEQ_QNA
START WITH 1
INCREMENT BY 1;

ALTER TABLE QNA
ADD CONSTRAINT FK_QNA_ID FOREIGN KEY(ID)
REFERENCES SEMI_MEMBER(ID);

CREATE TABLE BUYHISTORY(
	SEQ VARCHAR2 (100) not null, --상품번호
	ID VARCHAR2(50) NOT NULL, --판매자 ID
	PRODUCT_NAME VARCHAR2(100), --상품이름
	BUYER VARCHAR2(100), --구매자
	START_PRICE NUMBER, --현재가
	SELL_STATUS NUMBER -- 입찰진행상태
);

ALTER TABLE BUYHISTORY
ADD CONSTRAINT FK_BUY_ID FOREIGN KEY(ID)
REFERENCES SEMI_MEMBER(ID);

ALTER TABLE BUYHISTORY
ADD CONSTRAINT FK_BUY_SEQ FOREIGN KEY(SEQ)
REFERENCES PRODUCT(SEQ);
